---
- name: Installing java 
  yum:
    name: {{ item }}
	state: latest
  loop:
    - java-11-openjdk-devel
    - git 

- name: Download & Install maven 
  unarchive:
    src: https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: /usr/local/apache-maven/apache-maven-{{ maven_version }}
    remote_src: yes

- name: Configure maven home and environment variables
  template:
    src: maven.j2
    dest: /etc/profile.d/maven.sh

- name: Refresh environment variables
  shell: source /etc/profile.d/maven.sh

- name: Create application folder 
  file:
    path: {{ app_path }}
    state: directory

- name: Configure java app service 
  template:
    src: javaservice.j2
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Clone git code 
  git:
    repo: {{ app_git_url }}
    dest: /tmp/{{ app_name }}
  register: git_clone_status

- name: Maven build 
  shell: mvn --quiet clean install
  args:
     chdir: "/tmp/{{ app_name }}"  
  when: git_clone_status.changed
  register: mvn_build_status

- name: copy artifact to app folder
  copy:
    src: "/tmp/{{ app_name }}/target/*.jar" 
    dest: "{{ app_path }}/app.jar"
  when: mvn_build_status.changed
  register: artifact_status

- name: Start application
  systemd_service:
    name: {{ app_name }}
    daemon_reload: true
    state: restarted
  when: artifact_status.changed




